#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#

# The search paths for the included middleware
SEARCH_retarget-io=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/retarget-io/latest-v1.X

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_retarget-io)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_RETARGET_IO

# Build-system libs (added for offline build)
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CAT1CM0P


#
# generate make targets for the graphical editors that are specific to this project
#

.PHONY: mtb_help_tools_start mtb_help_tools_end
# Build-system libs (added for offline build)
SEARCH_mtb-hal-cat1=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-hal-cat1/release-v2.7.4
SEARCH_mtb-pdl-cat1=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-pdl-cat1/release-v3.23.0
SEARCH_core-lib=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-lib/release-v1.8.0
SEARCH_cmsis=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cmsis/release-v6.1.0
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_TARGET_CY8CKIT-062-BLE)
SEARCH_MTB_MK+=$(SEARCH_TARGET_CY8CKIT-062-BLE)/config
SEARCH_MTB_MK+=$(SEARCH_TARGET_CY8CKIT-062-BLE)/config/GeneratedSource
