#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
bsp-assistant config device-configurator dfuh-tool config_ezpd ez-pd-configurator modlibs library-manager qspi-configurator seglcd-configurator smartio-configurator config_usbdev usbdev-configurator capsense-configurator capsense-tuner edge-protect-configurator :
	make -C eink_test $@

config_bt bt-configurator config_lin lin-configurator config_ml deepcraftmodelconverter secure-policy-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: bsp-assistant config_bt bt-configurator config device-configurator dfuh-tool config_ezpd ez-pd-configurator modlibs library-manager config_lin lin-configurator qspi-configurator seglcd-configurator smartio-configurator config_usbdev usbdev-configurator config_ml capsense-configurator capsense-tuner deepcraftmodelconverter secure-policy-configurator edge-protect-configurator
