#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#

# The search paths for the included middleware
SEARCH_display-eink-e2271cs021=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/display-eink-e2271cs021/release-v1.1.0
SEARCH_retarget-io=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/retarget-io/latest-v1.X

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_display-eink-e2271cs021)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_DISPLAY_EINK_E2271CS021
COMPONENTS += MW_RETARGET_IO


#
# generate make targets for the graphical editors that are specific to this project
#

.PHONY: mtb_help_tools_start mtb_help_tools_end
