#!/usr/bin/env python3
"""Build the S25FL512S probe-rs flash algorithm and generate a target YAML.

Compiles flash_s25fl512s_smif.c (position-independent, register-level PSoC6
SMIF, single-SPI 4-byte-address commands) with arm-none-eabi-gcc, extracts
the code blob + entry-point offsets, and writes target_cy8c6347_smif.yaml for
use with:

  probe-rs download --chip-description-path target_cy8c6347_smif.yaml \
      --chip CY8C6347BZI-BLD53-S25FL512S --binary-format hex app.hex

Usage: python build_algo.py [page_size_hex]
"""
import base64
import subprocess
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GCC = r"D:/arm-none-eabi-tc/bin/arm-none-eabi-gcc.exe"
LD = r"D:/arm-none-eabi-tc/bin/arm-none-eabi-ld.exe"
NM = r"D:/arm-none-eabi-tc/bin/arm-none-eabi-nm.exe"
OBJCOPY = r"D:/arm-none-eabi-tc/bin/arm-none-eabi-objcopy.exe"

LOAD = 0x08000000       # link base (algo.ld) - offsets are relative to this
RUNTIME_LOAD = 0x08000020  # runtime load point (probe-rs prepends a 4-byte BKPT header)


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"command failed: {' '.join(cmd)}\n{r.stderr}")
    return r.stdout


def main() -> int:
    page_size = int(sys.argv[1], 0) if len(sys.argv) > 1 else 0x1000
    run([GCC, "-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=soft",
         "-ffreestanding", "-fno-builtin", "-fno-stack-protector",
         "-fomit-frame-pointer", "-O2", "-Wall", "-c",
         "flash_s25fl512s_smif.c", "-o", "flash.o"])
    run([LD, "-T", "algo.ld", "flash.o", "-o", "flash.elf"])
    run([OBJCOPY, "-O", "binary", "flash.elf", "flash.bin"])

    blob = open(os.path.join(HERE, "flash.bin"), "rb").read()
    b64 = base64.b64encode(blob).decode()

    # symbol -> offset (from the linked base 0x08000000)
    nm = run([NM, "-n", "flash.elf"])
    sym = {}
    for line in nm.splitlines():
        parts = line.split()
        if len(parts) == 3:
            addr, _typ, name = int(parts[0], 16), parts[1], parts[2]
            sym[name] = addr - LOAD

    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        if fn not in sym:
            sys.exit(f"symbol {fn} not found")

    yaml = f"""# Auto-generated by build_algo.py - CY8C6347 S25FL512S SMIF algorithm.
name: CY8C6347BZI-BLD53 S25FL512S SMIF
variants:
  - name: CY8C6347BZI-BLD53-S25FL512S
    package_variants:
      - CY8C6347BZI-BLD53
    cores:
      - name: cm0p
        type: armv6m
        core_access_options: !Arm
          ap: !v1 1
      - name: cm4
        type: armv7em
        core_access_options: !Arm
          ap: !v1 2
    memory_map:
      - !Ram
        name: SRAM
        range:
          start: 0x08000000
          end: 0x08048000
        cores:
          - cm0p
          - cm4
      - !Nvm
        name: S25FL512S
        range:
          start: 0x18000000
          end: 0x1c000000
        cores:
          - cm4
        access:
          write: false
          boot: true
    flash_algorithms:
      - smif_s25fl512s
flash_algorithms:
  - name: smif_s25fl512s
    description: S25FL512S 64MB via PSoC6 SMIF (single SPI, 4-byte addr)
    default: true
    instructions: {b64}
    load_address: 0x{LOAD + 0x20:X}
    pc_init: 0x{sym['Init']:X}
    pc_uninit: 0x{sym['UnInit']:X}
    pc_program_page: 0x{sym['ProgramPage']:X}
    pc_erase_sector: 0x{sym['EraseSector']:X}
    pc_erase_all: 0x{sym['EraseChip']:X}
    pc_verify: 0x{sym['Verify']:X}
    data_section_offset: 0x0
    stack_size: 0x800
    flash_properties:
      address_range:
        start: 0x18000000
        end: 0x1c000000
      page_size: 0x{page_size:X}
      erased_byte_value: 0xff
      program_page_timeout: 5000
      erase_sector_timeout: 10000
      sectors:
        - size: 0x40000
          address: 0x0
"""

    with open(os.path.join(HERE, "target_cy8c6347_smif.yaml"), "w") as fh:
        fh.write(yaml)

    size = run([NM, "-S", "--size-sort", "flash.elf"])
    print(size)
    print(f"blob: {len(blob)} bytes -> target_cy8c6347_smif.yaml")
    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        print(f"  {fn}: offset 0x{sym[fn]:X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
