#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#

# The search paths for the included middleware
SEARCH_capsense=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/capsense/release-v10.0.0
SEARCH_retarget-io=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/retarget-io/latest-v1.X

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_capsense)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_CAPSENSE
COMPONENTS += MW_RETARGET_IO


#
# generate make targets for the graphical editors that are specific to this project
#

.PHONY: mtb_help_tools_start mtb_help_tools_end
