################################################################################
# \file defines.mk
#
# \brief
# Defines, needed for the PSOC(TM) 6 build recipe.
#
################################################################################
# \copyright
# Copyright (c) 2018-2026, Infineon Technologies AG, or an affiliate of
# Infineon Technologies AG. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

include $(MTB_TOOLS__RECIPE_DIR)/make/recipe/defines_common.mk


################################################################################
# General
################################################################################
_MTB_RECIPE__PROGRAM_INTERFACE_SUPPORTED:=KitProg3 JLink
_MTB_RECIPE__DEFAULT_PROGRAM_INTERFACE:=KitProg3
#
# Compatibility interface for this recipe make
#
MTB_RECIPE__INTERFACE_VERSION:=2
MTB_RECIPE__EXPORT_INTERFACES:=1 2 3 4 5

MTB_RECIPE__NINJA_SUPPORT:=1 2

#
# List the supported toolchains
#
ifdef CY_SUPPORTED_TOOLCHAINS
MTB_SUPPORTED_TOOLCHAINS?=$(CY_SUPPORTED_TOOLCHAINS)
else
MTB_SUPPORTED_TOOLCHAINS?=GCC_ARM IAR ARM A_Clang LLVM_ARM
endif

# For BWC with Makefiles that do anything with CY_SUPPORTED_TOOLCHAINS
CY_SUPPORTED_TOOLCHAINS:=$(MTB_SUPPORTED_TOOLCHAINS)

_MTB_RECIPE__START_FLASH:=0x10000000

ifeq ($(MTB_TYPE),PROJECT)
_MTB_RECIPE__IS_MULTI_CORE_APPLICATION:=true
endif

# Supported XMC platforms:
_MTB_RECIPE__SUPPORTED_XMC_PLATFORMS=XMC5100 XMC5200 XMC5300

ifneq (,$(filter $(_MTB_RECIPE__SUPPORTED_XMC_PLATFORMS),$(MTB_CORE__FULL_COMPONENT_LIST)))
_MTB_RECIPE__IS_XMC5000_DEVICE:=true
else ifeq ($(filter TVIIBE% TVIICE%,$(_MTB_RECIPE__DEVICE_DIE)),$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__TVII_DEVICE:=true
else
_MTB_RECIPE__IS_PSOC6_DEVICE:=true
endif

#
# Core specifics
#
_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE:=run

ifeq (,$(_MTB_RECIPE__IS_MULTI_CORE_DEVICE))
ifeq ($(MTB_RECIPE__CORE),CM0P)
$(call mtb__error,$(DEVICE) does not have a CM0+ core)
endif
_MTB_RECIPE__OPENOCD_CORE:=cm4
_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG:=
_MTB_RECIPE__OPENOCD_EXTRA_PORT_ECLIPSE:=
_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG:=set ENABLE_CM0 0
_MTB_RECIPE__OPENOCD_CM0_DISABLE_ECLIPSE:=-c &quot;$(_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG)&quot;&\#13;&\#10;
_MTB_RECIPE__OPENOCD_GDBINIT_FILE:=gdbinit
_MTB_RECIPE__JLINK_GDBINIT_FILE:=gdbinit_jlink
else
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__OPENOCD_CORE:=cm0
_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE:=init
_MTB_RECIPE__OPENOCD_GDBINIT_FILE:=gdbinit_cm0
_MTB_RECIPE__JLINK_GDBINIT_FILE:=gdbinit_cm0_jlink

else
_MTB_RECIPE__OPENOCD_CORE:=cm4
_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG:=gdb_port 3332
_MTB_RECIPE__OPENOCD_EXTRA_PORT_ECLIPSE:=-c &quot;$(_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG)&quot;&\#13;&\#10;
_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG:=
_MTB_RECIPE__OPENOCD_CM0_DISABLE_ECLIPSE:=
_MTB_RECIPE__OPENOCD_GDBINIT_FILE:=gdbinit
_MTB_RECIPE__JLINK_GDBINIT_FILE:=gdbinit_jlink
endif
endif #(,$(_MTB_RECIPE__IS_MULTI_CORE_DEVICE))

#
# Secure targets specifics
#
ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))
_MTB_RECIPE__OPENOCD_GDBINIT_FILE:=gdbinit_secure
_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG:=
_MTB_RECIPE__OPENOCD_EXTRA_PORT_ECLIPSE:=
_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE:=init
_MTB_RECIPE__OPENOCD_DO_CONTINUE:=true
_MTB_RECIPE__OPENOCD_SET_STOP_AT:=true
_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_DEBUG_ECLIPSE:=mon reset $(_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE)&\#13;&\#10;flushregs
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__OPENOCD_TARGET_AP:=set TARGET_AP cm0_ap
else
_MTB_RECIPE__OPENOCD_TARGET_AP:=set TARGET_AP cm4_ap
_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG:=set TARGET_AP cm4_ap
_MTB_RECIPE__CM0_CM4_ELF_FILE_APPLICATION:=$(_MTB_RECIPE__VSCODE_ELF_FILE_APPLICATION)
ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG:=gdb_port 3332;set TARGET_AP cm0_cm4_ap
_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_DEBUG_ECLIPSE:=mon reset $(_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE)&\#13;&\#10;flushregs&\#13;&\#10;monitor targets psoc64.cpu.cm0&\#13;&\#10;monitor resume&\#13;&\#10;monitor targets psoc64.cpu.cm4
endif
endif # ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE:=flushregs
_MTB_RECIPE__OPENOCD_SMIF_DISABLE:=set DISABLE_SMIF 1
_MTB_RECIPE__OPENOCD_SMIF_DISABLE_ECLIPSE:=-c &quot;$(_MTB_RECIPE__OPENOCD_SMIF_DISABLE)&quot;&\#13;&\#10;
_MTB_RECIPE__OPENOCD_TARGET_AP_ECLIPSE:=-c &quot;$(_MTB_RECIPE__OPENOCD_TARGET_AP)&quot;&\#13;&\#10;
_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG_ECLIPSE:=-c &quot;$(_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG)&quot;&\#13;&\#10;
CY_OPENOCD_SHELL_TIMEOUT_CMD:=shell sleep 5
CY_OPENOCD_SHELL_TIMEOUT_ECLIPSE:=$(CY_OPENOCD_SHELL_TIMEOUT_CMD)&\#13;&\#10;
_MTB_RECIPE__MULTICORE_SECOND_CONFIG_ECLIPSE:=Add CM0+ to CM4
_MTB_RECIPE__MULTICORE_SECOND_CONFIG_VSCODE:=CM0+
else # ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))
_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_DEBUG_ECLIPSE=mon reset $(_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE)&\#13;&\#10;mon $(_MTB_RECIPE__OPENOCD_MONITOR_CMDS_NAME) reset_halt sysresetreq&\#13;&\#10;flushregs&\#13;&\#10;mon gdb_sync&\#13;&\#10;thread apply all stepi&\#13;&\#10;tbreak main&\#13;&\#10;thread apply all continue
_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE:=flushregs&\#13;&\#10;mon gdb_sync&\#13;&\#10;thread apply all stepi
_MTB_RECIPE__MULTICORE_SECOND_CONFIG_ECLIPSE:=Add CM4 to CM0+
_MTB_RECIPE__MULTICORE_SECOND_CONFIG_VSCODE:=CM4
_MTB_RECIPE__OPENOCD_DO_CONTINUE:=false
_MTB_RECIPE__OPENOCD_SET_STOP_AT:=false
_MTB_RECIPE__OPENOCD_CM0_RTOS_ECLIPSE_CMD=-c &quot;$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm0 configure -rtos auto -rtos-wipe-on-reset-halt 1&quot;&\#13;&\#10;
_MTB_RECIPE__OPENOCD_CM4_RTOS_ECLIPSE_CMD=-c &quot;$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm4 configure -rtos auto -rtos-wipe-on-reset-halt 1&quot;&\#13;&\#10;
endif

#
# Architecture specifics
#
_MTB_RECIPE__OPENOCD_MONITOR_CMDS_NAME:=psoc6
_MTB_RECIPE__MCU_NAME:=PSoC6

ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))

_MTB_RECIPE__OPENOCD_CHIP_NAME:=psoc64
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_CM4
_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE:=_CM4
_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX:=_tm
_MTB_RECIPE__JLINK_DEBUG_SUFFIX:=_tm
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_CM0p
endif

else ifneq (,$(_MTB_RECIPE__TVII_DEVICE))

# The MCU name drives the VS Code/Eclipse launch-config display names. Keep it as
# the human-readable family name ("TRAVEO T2G") for backward compatibility.
_MTB_RECIPE__MCU_NAME:=TRAVEO T2G

# Traveo T2G (TVII) devices use the device series name as the IAR device name.
# DEVICE_SERIES defined in the BSP takes precedence; otherwise the series is
# detected from the device die (and the part number where a single die spans
# multiple series, e.g. TVIIBE1M -> CYT2B6/CYT2B7).
ifneq (,$(DEVICE_SERIES))
_MTB_RECIPE__IAR_DEVICE_NAME:=$(DEVICE_SERIES)
else ifeq (TVIIBE1M,$(_MTB_RECIPE__DEVICE_DIE))
ifneq (,$(findstring CYT2B6,$(DEVICE)))
_MTB_RECIPE__IAR_DEVICE_NAME:=CYT2B6
else
_MTB_RECIPE__IAR_DEVICE_NAME:=CYT2B7
endif
else ifeq (TVIIBE2M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__IAR_DEVICE_NAME:=CYT2B9
else ifeq (TVIIBE4M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__IAR_DEVICE_NAME:=CYT2BL
else ifeq (TVIICE4M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__IAR_DEVICE_NAME:=CYT2CL
else
_MTB_RECIPE__IAR_DEVICE_NAME:=TRAVEO T2G
endif
_MTB_RECIPE__OPENOCD_MONITOR_CMDS_NAME:=traveo2

_MTB_RECIPE__FLASH_VAR:=$(DEVICE)
_MTB_RECIPE__NO_QSPI:=1
_MTB_RECIPE__JLINK_SECT:=
_MTB_RECIPE__JLINK_DEBUG_SUFFIX:=
_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX:=
_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE:=_M0
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_M4
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE=_M0
endif

else ifneq (,$(_MTB_RECIPE__IS_XMC5000_DEVICE))

_MTB_RECIPE__MCU_NAME=$(filter $(_MTB_RECIPE__SUPPORTED_XMC_PLATFORMS),$(MTB_CORE__FULL_COMPONENT_LIST))
_MTB_RECIPE__OPENOCD_MONITOR_CMDS_NAME:=xmc5xxx

_MTB_RECIPE__FLASH_VAR:=$(DEVICE)
_MTB_RECIPE__NO_QSPI:=1
_MTB_RECIPE__JLINK_SECT:=
_MTB_RECIPE__JLINK_DEBUG_SUFFIX:=
_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX:=
_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE:=_M0
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_M4
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE=_M0
endif

else #(,$(_MTB_RECIPE__IS_SECURE_DEVICE))

_MTB_RECIPE__OPENOCD_CHIP_NAME:=psoc6
_MTB_RECIPE__JLINKSCRIPT_SECT128:=_sect128KB
_MTB_RECIPE__JLINKSCRIPT_SECT256:=_sect256KB
ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_CM0p
_MTB_RECIPE__JLINK_DEBUG_SUFFIX:=_tm
else
_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE:=_CM4
_MTB_RECIPE__JLINK_DEBUG_SUFFIX:=
endif

ifeq (,$(_MTB_RECIPE__IS_MULTI_CORE_DEVICE))
_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX:=
_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE:=_CM4
else
_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX:=_tm
_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE:=_CM0p
endif

ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
_MTB_RECIPE__OPENOCD_CM0_RTOS_CONFIG=$(_MTB_RECIPE__OPENOCD_CM0_RTOS_ECLIPSE_CMD)
_MTB_RECIPE__OPENOCD_CM4_RTOS_CONFIG=$(_MTB_RECIPE__OPENOCD_CM4_RTOS_ECLIPSE_CMD)
endif

endif #(,$(_MTB_RECIPE__IS_SECURE_DEVICE))

ifeq (PSoC6ABLE2,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cy8c6xx.cfg
_MTB_RECIPE__JLINK_SECT:=$(_MTB_RECIPE__JLINKSCRIPT_SECT256)
ifeq (512,$(_MTB_RECIPE__DEVICE_FLASH_KB))
_MTB_RECIPE__FLASH_VAR:=CY8C6xx6
else #(512,$(_MTB_RECIPE__DEVICE_FLASH_KB))
_MTB_RECIPE__FLASH_VAR:=CY8C6xx7
endif #(512,$(_MTB_RECIPE__DEVICE_FLASH_KB))

ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))
_MTB_RECIPE__FLASH_VAR:=CYB06xx7
_MTB_RECIPE__JLINK_SECT:=
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cyxx64x7.cfg
endif

else ifeq (PSoC6A2M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cy8cxxa.cfg
_MTB_RECIPE__JLINK_SECT:=$(_MTB_RECIPE__JLINKSCRIPT_SECT256)
ifeq (1024,$(_MTB_RECIPE__DEVICE_FLASH_KB))
_MTB_RECIPE__FLASH_VAR:=CY8C6xx8
else #(1024,$(_MTB_RECIPE__DEVICE_FLASH_KB))
_MTB_RECIPE__FLASH_VAR:=CY8C6xxA
endif #(1024,$(_MTB_RECIPE__DEVICE_FLASH_KB))
ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))
_MTB_RECIPE__FLASH_VAR:=CYB06xxA
_MTB_RECIPE__JLINK_SECT:=
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cyxx64xa.cfg
endif

else ifeq (PSoC6A512K,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__FLASH_VAR:=CY8C6xx5
_MTB_RECIPE__JLINK_SECT:=$(_MTB_RECIPE__JLINKSCRIPT_SECT256)
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cy8cxx5.cfg
ifneq (,$(_MTB_RECIPE__IS_SECURE_DEVICE))
_MTB_RECIPE__FLASH_VAR:=CYB06xx5
_MTB_RECIPE__JLINK_SECT:=
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cyxx64x5.cfg
endif

else ifeq (FX3G2,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/fx3gx.cfg
_MTB_RECIPE__FLASH_VAR:=CYUSB401x
_MTB_RECIPE__JLINK_SECT:=$(_MTB_RECIPE__JLINKSCRIPT_SECT256)

else ifeq (PSoC6A256K,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__FLASH_VAR:=CY8C6xx4
_MTB_RECIPE__JLINK_SECT:=$(_MTB_RECIPE__JLINKSCRIPT_SECT128)
ifneq (,$(findstring CY8C45,$(DEVICE)))
_MTB_RECIPE__OPENOCD_CHIP_NAME:=psoc4500
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/psoc4500h.cfg
else
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cy8cxx4.cfg
endif

else ifeq (true,$(_MTB_RECIPE__TVII_DEVICE))

ifeq (TVIIBE1M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=traveo2_1m_a0.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=traveo2
else ifeq (TVIIBE2M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=traveo2_2m.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=traveo2
else ifeq (TVIIBE4M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=traveo2_be_4m.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=traveo2_be_4m
else ifeq (TVIICE4M,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/cyt2cl.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=traveo2_ce_4m
endif

else ifeq (true,$(_MTB_RECIPE__IS_XMC5000_DEVICE))

ifeq (XMC5100,$(_MTB_RECIPE__MCU_NAME))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/xmc5100.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=xmc5100
else ifeq (XMC5200,$(_MTB_RECIPE__MCU_NAME))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/xmc5200.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=xmc5200
else ifeq (XMC5300,$(_MTB_RECIPE__MCU_NAME))
_MTB_RECIPE__OPENOCD_DEVICE_CFG=infineon/xmc5300.cfg
_MTB_RECIPE__OPENOCD_CHIP_NAME:=xmc5300
endif

else
$(call mtb__error,Incorrect part number $(DEVICE). Check DEVICE variable.)
endif

_MTB_RECIPE__JLINK_DEVICE_CFG_PROGRAM:=$(_MTB_RECIPE__FLASH_VAR)$(_MTB_RECIPE__JLINKSCRIPT_PROGRAM_CORE)$(_MTB_RECIPE__JLINK_SECT)$(_MTB_RECIPE__JLINKSCRIPT_TM_POST_FIX)
_MTB_RECIPE__JLINK_DEVICE_CFG_ATTACH:=$(_MTB_RECIPE__FLASH_VAR)$(_MTB_RECIPE__JLINKSCRIPT_ATTACH_CORE)
_MTB_RECIPE__JLINK_DEVICE_CFG_DEBUG:=$(_MTB_RECIPE__JLINK_DEVICE_CFG_ATTACH)$(_MTB_RECIPE__JLINK_SECT)$(_MTB_RECIPE__JLINK_DEBUG_SUFFIX)
# Architecture specifics

ifneq ($(OTA_SUPPORT),)
# OTA post-build script needs python.
CY_PYTHON_REQUIREMENT=true
endif


_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_SECOND_CONFIG_NAME:=$(_MTB_RECIPE__MULTICORE_SECOND_CONFIG_ECLIPSE)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_CONTINUE:=$(_MTB_RECIPE__OPENOCD_DO_CONTINUE)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_STOP_AT:=$(_MTB_RECIPE__OPENOCD_SET_STOP_AT)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_SECOND_RESET_TYPE:=$(_MTB_RECIPE__OPENOCD_SECOND_RESET_TYPE)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_DEBUG_ECLIPSE)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_CLIENT_OTHER_COMMANDS = $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(call _MTB_RECIPE__MAKE_ECLIPSE_NEWLINE,set mem inaccessible-by-default off)\
	$(if $(CY_OPENOCD_SHELL_TIMEOUT_CMD),$(call _MTB_RECIPE__MAKE_ECLIPSE_NEWLINE,$(CY_OPENOCD_SHELL_TIMEOUT_CMD)),^)\
	$(call _MTB_RECIPE__MAKE_ECLIPSE_NO_NEWLINE,set remotetimeout 25))

ifeq ($(MTB_RECIPE__CORE),CM4)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET:=false

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_CUSTOM_COMMANDS = $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(if $(_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG)),^)\
	$(if $(_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD_LAST,$(_MTB_RECIPE__OPENOCD_TARGET_AP_DEBUG)),^))

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS = $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(if $(_MTB_RECIPE__OPENOCD_CM0_RTOS_CONFIG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm0 configure -rtos auto -rtos-wipe-on-reset-halt 1),^)\
	$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm4 configure -rtos auto -rtos-wipe-on-reset-halt 1))

_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS:=$(_MTB_RECIPE__OPENOCD_CM0_RTOS_CONFIG)$(_MTB_RECIPE__OPENOCD_CM4_RTOS_ECLIPSE_CMD)$(_MTB_RECIPE__OPENOCD_EXTRA_PORT_ECLIPSE)

else
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET:=true

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_CUSTOM_COMMANDS = $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(if $(_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CM0_DISABLE_FLAG)),^)\
	$(if $(_MTB_RECIPE__OPENOCD_TARGET_AP),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD_LAST,$(_MTB_RECIPE__OPENOCD_TARGET_AP)),^))

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS = $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm0 configure -rtos auto -rtos-wipe-on-reset-halt 1)\
	$(if $(_MTB_RECIPE__OPENOCD_CM4_RTOS_CONFIG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cpu.cm4 configure -rtos auto -rtos-wipe-on-reset-halt 1),^))

_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS:=$(_MTB_RECIPE__OPENOCD_CM0_RTOS_ECLIPSE_CMD)$(_MTB_RECIPE__OPENOCD_CM4_RTOS_ECLIPSE_CMD)$(_MTB_RECIPE__OPENOCD_EXTRA_PORT_ECLIPSE)

endif

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS += $(call _MTB_RECIPE__MAKE_ECLIPSE_NORMALIZE_COMMANDS, \
	$(if $(_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG),$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_EXTRA_PORT_FLAG)),^)\
	$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD,$(_MTB_RECIPE__OPENOCD_MONITOR_CMDS_NAME) sflash_restrictions 1)\
	$(call _MTB_RECIPE__MAKE_ECLIPSE_CMD_LAST,init; reset init;$(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY)))


_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_CUSTOM_COMMANDS=$(_MTB_RECIPE__OPENOCD_CM0_DISABLE_ECLIPSE)$(_MTB_RECIPE__OPENOCD_TARGET_AP_ECLIPSE)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_DEBUG_ECLIPSE)

# JLink

ifeq ($(MTB_RECIPE__CORE),CM0P)
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_PORT_NUMBER=2331
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SWO_PORT_NUMBER=2332
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_TELNET_PORT_NUMBER=2333
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_PORT_NUMBER=2331
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SWO_PORT_NUMBER=2332
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_TELNET_PORT_NUMBER=2333

_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_TYPE:=2
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SECOND_RESET_TYPE:=0
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_FIRST_RESET_TYPE:=2
else
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_PORT_NUMBER=2334
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SWO_PORT_NUMBER=2335
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_TELNET_PORT_NUMBER=2336
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_PORT_NUMBER=2334
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SWO_PORT_NUMBER=2335
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_TELNET_PORT_NUMBER=2336

_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_TYPE:=0
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SECOND_RESET_TYPE:=2
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_FIRST_RESET_TYPE:=0
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS:=monitor reset 0
endif

_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_SERVER_DEVICE_NAME=$(_MTB_RECIPE__JLINK_DEVICE_CFG_DEBUG)
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_SERVER_DEVICE_NAME=$(_MTB_RECIPE__JLINK_DEVICE_CFG_ATTACH)


_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_ALLOCATE_SEMIHOSTING_CONSOLE:=true

_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING:=false
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_GDB_CLIENT:=false
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_TELNET_CLIENT:=false

_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_INTERFACE_SPEED:=4000
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_INTERFACE_SPEED:=4000

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_SECOND_CONFIG_NAME=$(_MTB_RECIPE__MULTICORE_SECOND_CONFIG_ECLIPSE)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_POST_TARGET_COMMANDS=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS)

_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE)
